---
title: "HW4"
author: "Xinyi Wang"
date: "4/10/2023"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
```


#import packages
```{r, message=FALSE}
library("shinyWidgets")
library(plotly)
library(tidyr)
library(dplyr)
library(shiny)
library(gridExtra)
library(ggraph)
library(tidygraph)
library(mapproj)
library(patchwork)
library(ggplot2)
library(lubridate)
library(tidyverse)
library(feasts)
library(fpp2)
library(ggrepel)
library(knitr)
library(igraph)
library(ggraph)
```


#import data & data cleaning
```{r}
gross = read.csv("https://github.com/Xinyi-225/STAT-463-HW4/raw/main/Highest%20Holywood%20Grossing%20Movies.csv") %>% 
  mutate(License = ifelse(is.na(License), "Unrated", License),
         Date = str_split(`Title`, "\\("), 
         Title = gsub("\\s*\\(\\d+\\)", "", Title)) %>% 
  unnest_wider(Date,"_") %>% 
  select(-c(3,5,12)) %>% 
  mutate(Date_2 = gsub("\\)$", "", Date_2)) %>% 
  rename("Year_Released" = "Date_2") %>% 
  mutate(Genre = gsub("\\[|\\]", "", Genre),
         Genre = gsub("'", "", Genre)) %>% 
  rename("Domestic Sales" = "Domestic.Sales..in...",
         "International Sales" = "International.Sales..in...",
         "World Sales" = "World.Sales..in...")
gross
```


#node and link diagram

```{r}
normalization <- function(x) {
    (x - min(x)) / (max(x) - min(x))
  }
gross_norm = as.data.frame(lapply(gross[c(4,5,6)], normalization))

gross_tree=
  as_tbl_graph(hclust(dist(gross_norm))) %>% 
  #The `dist` function below computes the pairwise distances between trajectories, and this is then fed into a hierarchical clustering routine by using hclust().
  activate(nodes) %>%
  mutate(Title=gross$Title[as.numeric(label)], 
         Year=gross$Year_Released[as.numeric(label)],
         License=gross$License[as.numeric(label)])

ggraph(gross_tree,layout = "kk")+
  geom_edge_link()+
  theme_graph()+
  geom_node_point(aes(col=License, filter=leaf))+
  theme(legend.text = element_text(size = 10), # set legend text size
        legend.title = element_text(size = 12), # set legend title size
        plot.margin = unit(c(0.1, 0.1, 0.1, 0.1), "cm"))+
  scale_color_discrete(breaks = c("G", "R", "PG", "PG-13", "Unrated"))

```



```{r,fig.width = 12,fig.height = 12}
source=c()
target=c()
for(i in 1:918){
  a=strsplit(gross$Genre[i],",")[[1]]
  for(val in a){
    val=gsub(" ", "", val, fixed = TRUE)
    source=append(source,val)
    target=append(target,gross$Title[i])
  }
}
Genre=data.frame(source=source,target=target)

Genre_tree=
  tbl_graph(edges = Genre) %>% 
  activate(nodes)%>%
  mutate(Topic=name %in% Genre$source)%>%
  mutate(Name=ifelse(Topic,name,NA))

ggraph(Genre_tree, layout = "fr") +
  geom_edge_link(arrow.size = 0.0001, alpha = 0.5) +
  theme_graph() +
  geom_node_point(col = "red") +
  geom_node_label(aes(label = Name)) +
  theme(plot.margin = unit(c(0.02, 0.02, 0.02, 0.02), "cm"))

```



```{r}
gross_long =
  pivot_longer(gross,cols = c("Domestic Sales", 
                                        "International Sales", 
                                        "World Sales"), 
                         names_to = "sales_range", 
                         values_to = "sales_value") %>% 
  mutate(Year_Released = as.integer(Year_Released))
```

```{r}
theme_set(theme_bw())
```


#original barplots
```{r,fig.width = 10}
plot1 = 
  gross_long %>% 
  ggplot(aes(Year_Released, sales_value)) +
  geom_bar(aes(fill = License), stat = "identity") +
  facet_wrap(~ sales_range, scales = "free_y") +
  scale_y_continuous(expand = c(0, 0, 0, 0)) +
  labs(x = "Year", y = "Sales", title = "Sales vs. Year") +
  theme(axis.line = element_line(color = "black"),
        axis.text = element_text(color = "black"),
        axis.title = element_text(color = "black"),
    axis.text.x = element_text(angle = 90),
    plot.title = element_text(size = 20))+
  scale_x_continuous(breaks = seq(min(gross_long$Year_Released), max(gross_long$Year_Released), by = 6))
plot1


word = 
  gross_long %>% 
  mutate(Genre = str_split(Genre, "\\s*,\\s*")) %>% 
  unnest(Genre) %>% 
  mutate(Genre = str_to_lower(Genre)) %>% 
  count(Genre)
plot2 = ggplot(word, aes(n, reorder(Genre,n))) +
  geom_col(fill = "lightgray") +
  labs(x = "Genre", y = "Count", title = "Genre vs. Year")+
  scale_y_discrete(expand = c(0, 0, 0, 0)) +
  scale_x_continuous(expand = c(0, 0, 0.1, 0)) +
  theme(
    axis.line = element_line(color = "black"),
    plot.title = element_text(size = 20))
ggplotly(plot2, tooltip = c("x", "Count"))

license_levels = c("Unrated","PG-13","PG","R","G")
word1 = 
  gross_long %>% 
  filter(Year_Released == 2015) %>% 
  count(License)
plot3 = ggplot(word1, aes(n, reorder(License,n))) +
  geom_col(fill = "lightgray", width = 0.6) +
  labs(x = "License", y = "Count", title = "License vs. Year")+
  scale_y_discrete(expand = c(0, 0, 0, 0)) +
  scale_x_continuous(expand = c(0, 0, 0.1, 0)) +
  theme(
    axis.line = element_line(color = "black"),
    plot.title = element_text(size = 20))+
  scale_y_discrete(limits = license_levels)
ggplotly(plot3, tooltip = c("x", "Count"))
```


#set unqiue inputs
```{r}
year <- pull(gross_long, Year_Released) %>%
  unique() %>%
  na.omit()

License = pull(gross_long, License) %>%
  unique() %>%
  na.omit()
```


#generate functions
```{r,fig.width = 15}
word_count = function(df) {
  df %>% 
    filter(selected) %>% 
    mutate(Genre = str_split(Genre, "\\s*,\\s*")) %>% 
    unnest(Genre) %>% 
    mutate(Genre = str_to_lower(Genre)) %>% 
    count(Genre)
}


Licence_count = function(df){
  df %>% 
  filter(selected) %>% 
    count(License)
}


state_alpha <- function(df) {
  df %>%
    ggplot(aes(Year_Released, sales_value, alpha = selected)) +
    geom_bar(aes(fill = License), stat = "identity") +
    facet_wrap(~ sales_range, scales = "free_y") +
    labs(x = "Year", y = "Sales", title = "Sales vs. Year") +
    scale_y_continuous(expand = c(0, 0, 0, 0)) +
  theme(axis.line = element_line(color = "black"),
        axis.text = element_text(color = "black"),
        axis.title = element_text(color = "black"),
    axis.text.x = element_text(angle = 90),
    plot.title = element_text(size = 20))+
    scale_x_continuous(breaks = seq(min(gross_long$Year_Released), max(gross_long$Year_Released), by = 6))
}
```


#main code
```{r}
ui <- fluidPage(
  tags$h2("Top 1000 Best-selling Hollywood Movies"),
  tags$p("The shiny visualizes sales, genre, and license distribution of these best-selling movies from 1937 to 2021 by allowing users to select multiple years."),
  setBackgroundColor(
    color = c("skyblue","violet", "pink","orange","yellow"),
    gradient = "linear",
    direction = "bottom"
  ),
  selectInput("years", "Years", choices = sort(year), multiple = TRUE),
  fluidRow(
  plotOutput("main_barplot"),
  plotlyOutput("genre_barplot"),
  plotlyOutput("license_barplot"))
)

server <- function(input, output) {

  year1 = reactive({
    gross_long %>%
      mutate(selected = Year_Released %in% input$years)})
  
  year2 = reactive({
  gross_long %>%
    filter(Year_Released %in% input$years) %>% 
    mutate(selected = TRUE)})
  
  
output$main_barplot <- renderPlot({
  if (is.null(input$years)) {
    main_barplot <- plot1
  } else {
    main_barplot <- state_alpha(year1())
  }
  main_barplot
})

  
  output$license_barplot <- renderPlotly({
    if (is.null(input$years)) {
      license_barplot = plot3
    } else {
      license_barplot = 
        Licence_count(year2()) %>% 
        ggplot(aes(n, reorder(License,n))) +
        geom_col(fill = "lightgray", width = 0.6) +
        labs(x = "License", y = "Count", title = "License vs. Year")+
        scale_y_discrete(expand = c(0, 0, 0, 0)) +
        scale_x_continuous(expand = c(0, 0, 0.1, 0)) +
        theme(axis.line = element_line(color = "black"),
              plot.title = element_text(size = 20))+
        scale_y_discrete(limits = license_levels)
    }
    license_barplot
  })
  
  output$genre_barplot <- renderPlotly({
    if (is.null(input$years)) {
      genre_barplot = plot2
    } else {
      genre_barplot = 
        word_count(year2()) %>% 
        ggplot(aes(n, reorder(Genre,n))) +
        geom_col(fill = "lightgray") +
        labs(x = "Genre", y = "Count", title = "Genre vs. Year") +
        scale_y_discrete(expand = c(0, 0, 0, 0)) +
        scale_x_continuous(expand = c(0, 0 , 0.1, 0)) +
        theme(axis.line = element_line(color = "black"),
              plot.title = element_text(size = 20))
    }
    genre_barplot
  })
  
  
}

app = shinyApp(ui, server)

```



